# Generated by Django 3.1.5 on 2021-01-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210113_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='heading',
            field=models.CharField(default='Heading', max_length=40, null=True),
        ),
    ]
