# Generated by Django 3.1.5 on 2021-01-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20210113_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
