# Generated by Django 3.1.5 on 2021-01-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210113_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.CharField(max_length=40),
        ),
    ]
